### ISSUE TITLE
How to start the program?

### ISSUE THREAD

**Issue by liamarliana3** [hungqcao/chegg-solutions-saver#2]
I am new to his. How to start the program? I can't find any exe file.

**Comment by hungqcao** [comment]
You can go to the release tab at https://github.com/hungqcao/chegg-solutions-saver/releases
And download the latest version.

**Comment by liamarliana3** [comment]
Thank you

I download the file and follow the instruction but got error : 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.BadImageFormatException: Could not load file or assembly 'CefSharp.WinForms, Version=75.1.143.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. An attempt was made to load a program with an incorrect format.
File name: 'CefSharp.WinForms, Version=75.1.143.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at CheggSolutionsCrawlerNetCore.Form1.InitializeChromium()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at CheggSolutionsCrawlerNetCore.Form1.InitializeChromium()
   at CheggSolutionsCrawlerNetCore.Form1.btnExecute_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)




************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.46205
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Private.CoreLib.dll
----------------------------------------
CheggSolutionsCrawlerNetCore
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/CheggSolutionsCrawlerNetCore.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.19.46210
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Collections.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Runtime.Extensions.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Diagnostics.Debug.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.19.46210
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.3.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Buffers.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Collections.NonGeneric.dll
----------------------------------------
System.Memory
    Assembly Version: 4.2.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Memory.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Resources.ResourceManager.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.14.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Collections.Concurrent.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Threading.Tasks.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Threading.ThreadPool.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.4.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Reflection.Metadata.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.IO.FileSystem.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.4.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/IIPAHM~1/AppData/Local/Temp/.net/CheggSolutionsCrawlerNetCore/pg24eswn.dts/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by hungqcao** [comment]
Can you try version 1.1?

**Comment by sofia-kyr** [comment]
Hi!!
Thanks for the effort you have put into this!
I tried both versions and followed each direction but I eventually see nothing on the output folder.
What do you think might happen?

**Comment by hungqcao** [comment]
Hi @sofia-kyr 
Did you see any error? Can you take a screenshot or something like that?
