### ISSUE TITLE
Issues using both Release 1.1 and .net Core versions

### ISSUE THREAD

**Issue by ceandrade** [hungqcao/chegg-solutions-saver#3]
Hi, 

I'm trying to download some solutions, but I have no succes on it. Using Release 1.1, I get no errors but it looks like the crawler only opens the first page and does nothing. The application looks be static (not frozen) and the output folder is never populated.

This is before I click "Execute":
![Screen Shot 2020-05-01 at 14 23 43](https://user-images.githubusercontent.com/722355/80830946-e70ebc00-8bb7-11ea-9c0b-b19ff66c073f.png)

Then, I got this and it is static:

![Screen Shot 2020-05-01 at 14 26 07](https://user-images.githubusercontent.com/722355/80830841-b4fd5a00-8bb7-11ea-84ef-f1343c83750a.png)

This is the error log:

```log
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WindowsFormsApp1.MainForm.<Crawl>d__6.MoveNext() in C:\Projects\chegg-solutions-saver\src\CheggSolutionsCrawler\MainForm.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WindowsFormsApp1.MainForm.<LoopThroughEachSolution>d__4.MoveNext() in C:\Projects\chegg-solutions-saver\src\CheggSolutionsCrawler\MainForm.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WindowsFormsApp1.MainForm.<InitializeChromium>d__1.MoveNext() in C:\Projects\chegg-solutions-saver\src\CheggSolutionsCrawler\MainForm.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WindowsFormsApp1
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/temp/CheggCrawler/WindowsFormsApp1.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CefSharp.WinForms
    Assembly Version: 71.0.0.0
    Win32 Version: 71.0.0.0
    CodeBase: file:///C:/temp/CheggCrawler/x86/CefSharp.WinForms.DLL
----------------------------------------
CefSharp.Core
    Assembly Version: 71.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/temp/CheggCrawler/x86/CefSharp.Core.DLL
----------------------------------------
CefSharp
    Assembly Version: 71.0.0.0
    Win32 Version: 71.0.0.0
    CodeBase: file:///C:/temp/CheggCrawler/x86/CefSharp.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.8.14.0
    Win32 Version: 1.8.14
    CodeBase: file:///C:/temp/CheggCrawler/HtmlAgilityPack.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

So, I have followed the instructions, logout before execute, but nothing works.

Using .net Core version, I got the following problem:

![Screen Shot 2020-05-01 at 14 19 37](https://user-images.githubusercontent.com/722355/80830352-cc881300-8bb6-11ea-8013-5485a2a6f048.png)

Thank you very much!

**Comment by hungqcao** [comment]
@ceandrade I'm looking into this. Thanks for reporting!

**Comment by hungqcao** [comment]
@ceandrade Please try this release and let me know how it goes https://github.com/hungqcao/chegg-solutions-saver/releases/tag/v1

**Comment by ceandrade** [comment]
Hey @hungqcao, it didn't work. I got the same error:

![Screen Shot 2020-05-09 at 08 14 16](https://user-images.githubusercontent.com/722355/81473575-5d6d7880-91cd-11ea-967e-2361ec946252.png)

Here is the log:

 See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WindowsFormsApp1.MainForm.<Crawl>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WindowsFormsApp1.MainForm.<LoopThroughEachSolution>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WindowsFormsApp1.MainForm.<InitializeChromium>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WindowsFormsApp1
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/hungcq@live.com/CheggCrawler/WindowsFormsApp1.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CefSharp.WinForms
    Assembly Version: 71.0.0.0
    Win32 Version: 71.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/hungcq@live.com/CheggCrawler/CefSharp.WinForms.DLL
----------------------------------------
CefSharp.Core
    Assembly Version: 71.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/hungcq@live.com/CheggCrawler/CefSharp.Core.DLL
----------------------------------------
CefSharp
    Assembly Version: 71.0.0.0
    Win32 Version: 71.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/hungcq@live.com/CheggCrawler/CefSharp.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.8.14.0
    Win32 Version: 1.8.14
    CodeBase: file:///C:/Program%20Files%20(x86)/hungcq@live.com/CheggCrawler/HtmlAgilityPack.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by hungqcao** [comment]
@ceandrade can you send me the url of the solution that you used? They probably changed the layout or something like that. Would it be ok for you to share your chegg account? You can change the password after that. My account is inactive so I can't really debug anything. Unless you can send me the whole HTML of the page

**Comment by ceandrade** [comment]
Sorry, I got messed up with other things, and indeed, I have no more access to Chegg. I'll try something in Aug or so. Many thanks for your help and coding!

**Comment by hungqcao** [comment]
No worries, I made some attempts to fix it in the new version 👍
