### ISSUE TITLE
How to start the program

### ISSUE THREAD

**Issue by tan-yong-sheng** [hungqcao/chegg-solutions-saver#4]
![Annotation 2020-05-05 172701](https://user-images.githubusercontent.com/64836390/81052320-cf0ba500-8ef5-11ea-8d3b-8dddbb9a024d.png)

 Actually how to start this program. Could not reach the 3rd step as you show (i.e. OPEN THE PROGRAM and copy the url into the program)

**Comment by hungqcao** [comment]
@tys203831 did you get any error?

**Comment by hungqcao** [comment]
Please try to install using https://github.com/hungqcao/chegg-solutions-saver/releases/tag/v1
