### ISSUE TITLE
"no solution" issue

### ISSUE THREAD

**Issue by Fycbicbeth** [hungqcao/chegg-solutions-saver#5]
The program successfully loads the page & logs in, it then proceeds to sequentially load each solution page. At the beginning of each chapter the program creates a folder, the first is "Chapter 1", and after it has scraped the information from the last question in the chapter it creates a file in the folder "Chapter 1" called "-nosolution.html". The file contains a single line of text which is "no solution".

When the program has the answer pages loaded, a popup appears. I'm not sure if this has any effect, whether I close it or leave it open I still have the same issue.

I have installed the program using the latest .msi installer, and also have Visual C++ Runtime 2013 installed on my machine (both 32 and 64 bit).

![Screenshot (102)](https://user-images.githubusercontent.com/37975024/83478350-fa73b680-a4d8-11ea-893b-dce9e58ebe82.png)
![Annotation 2020-06-02 134725](https://user-images.githubusercontent.com/37975024/83478360-fe073d80-a4d8-11ea-8a50-2948a89f1385.png)
![Annotation 2020-06-02 134829](https://user-images.githubusercontent.com/37975024/83478365-ffd10100-a4d8-11ea-919a-0ccb057e3301.png)

**Comment by hungqcao** [comment]
Interesting, it looks like the "new feature" pop up window did confuse the program. Can you close the pop up and run again? Please let me know how it goes

**Comment by Fycbicbeth** [comment]
Sorry I might not have been clear in the first post, but I have tried running it both ways; with the popup left alone, and with me closing the popup. Both give me the same outcome.

**Comment by hungqcao** [comment]
New release came out to address this issue. Thanks for bringing it up!
